-- AlterTable
ALTER TABLE "PlaygroundConfig" ADD COLUMN     "flBendRadius" DOUBLE PRECISION NOT NULL DEFAULT 5.0,
ADD COLUMN     "flBendStrength" DOUBLE PRECISION NOT NULL DEFAULT -0.5,
ADD COLUMN     "flLineCount" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN     "flLineDistance" DOUBLE PRECISION NOT NULL DEFAULT 5.0,
ADD COLUMN     "flParallax" BOOLEAN NOT NULL DEFAULT true;
